### PR TITLE
New york times clone

### PR DESCRIPTION
**Pull request by Shaher-11**
This is the new york times clone project and the project built with pure HTML and CSS without the help of any library or framework and you can also view the project live in the link provided in the readme file

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: INVALID 🔴 🟥 

### Hey there, 👋🏽 

I'm invalidating this PR because the PR does not have a meaningful title and a brief description.
Kindly visit the lesson and master how to do this. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Shaher-11**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] the nyt logo should be an actual logo not just text. [here](https://mwcm.nyt.com/.resources/mkt-wcm/dist/libs/assets/img/logo_nyt_white.svg) is a link for the svg.
- [x] the social buttons on the top of the page should also be links or clickable buttons.
- [x] there are 4 sections missing from the bottom of the page, please make sure to add them.

- [x] the page header should be an h1 tag.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by Shaher-11** [comment]
Done, The requested changes

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Shaher-11 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
